title: ğŸ´â€â˜ ï¸ğŸ¦† HS2 Guides
description: This is intended to be a temporary place to host my Hero Siege 2 guides, before I migrate them to the official wiki.
theme: just-the-docs

url: https://antistoopmode.github.io
color_scheme: dark

aux_links:
  Report Issue: https://github.com/antistoopmode/antistoopmode.github.io/issues
  Contribute: https://github.com/antistoopmode/antistoopmode.github.io

callouts:
  warning:
    title: Warning
    color: red